### PR TITLE
bump converse.js from 2.0.6 to 3.3.1

### PR DESCRIPTION
**Pull request by diditopher**

### CODE REVIEW

**Comment by devurandom** [comment]
I believe you also fixed the login issue that existed since a very long time. Thanks!

LGTM

**Comment by janmuennich** [comment]
With this version I have some problems logging in.

Prebind logs in successfully according to the XMPP server logs. But JS does not log in automatically after that. I found this in the browser console:
`WARNING: Could not restore session for jid: user@server.tld/Roundcube-5aabd53d1d0ef Error message: _restore: no restoreable session.`

Logging in manually afterwards works.

Can you reproduce the problem?

**Comment by jcbrand** [comment]
FYI, version 3.3.4 is already out since a while.

**Comment by diditopher** [comment]
current version also works with 3.3.4. All that needs to be changed is the last line in config.inc.php:
`$rcmail_config['converse_cdn'] = 'https://cdn.conversejs.org/3.3.1';`
to:
`$rcmail_config['converse_cdn'] = 'https://cdn.conversejs.org/3.3.4';`

**Pull request merged**
